language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pytest
  - pip install coverage
  - pip install coveralls
  - pip install numpy
# command to run tests
script: coverage run --source=sanedecayrescaling setup.py test
after_success:
  - coveralls
  - coverage report -m